# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      # Standalone deps
      - dependency-name: "mongodb"
      - dependency-name: "bson"
      # All the mongosh deps
      - dependency-name: "@mongosh/node-runtime-worker-thread"
      - dependency-name: "@mongosh/browser-repl"
      - dependency-name: "@mongosh/logging"
      # All the electron and its related deps
      - dependency-name: "electron"
      - dependency-name: "@electron/remote"
      - dependency-name: "@electron/rebuild"
      - dependency-name: "browserslist"
      - dependency-name: "node-abi"
    groups:
      electron-update:
        patterns:
        - "electron"
        - "@electron/remote"
        - "@electron/rebuild"
        - "browserslist"
        - "node-abi"
      mongosh-update:
        patterns:
        - "@mongosh/*"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "release notes"
