# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "mongodb"
      - dependency-name: "electron"
      - dependency-name: "@electron/remote"
      - dependency-name: "@electron/build"
      - dependency-name: "browserslist"
      - dependency-name: "node-abi"
    commit-message:
      prefix: "chore(deps): "
      include: "scope"
    labels:
      - "dependencies"
      - "release notes"
